// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0DH5LC41d5qA1n_hhx6GZTos-l9k-GI',
    appId: '1:134326297257:web:d3b474af5715766434bfb8',
    messagingSenderId: '134326297257',
    projectId: 'comments-app-b3777',
    authDomain: 'comments-app-b3777.firebaseapp.com',
    storageBucket: 'comments-app-b3777.appspot.com',
    measurementId: 'G-1EPB7GRTH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BpnBYbMC-qom-7UbDN0TxxGEzL7I00A',
    appId: '1:134326297257:android:abb1bf260acd3c2d34bfb8',
    messagingSenderId: '134326297257',
    projectId: 'comments-app-b3777',
    storageBucket: 'comments-app-b3777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4J7Ky2ywpzrgXamZp_y1jEjpUYQ2hxdo',
    appId: '1:134326297257:ios:d1146fbbbb0f522a34bfb8',
    messagingSenderId: '134326297257',
    projectId: 'comments-app-b3777',
    storageBucket: 'comments-app-b3777.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4J7Ky2ywpzrgXamZp_y1jEjpUYQ2hxdo',
    appId: '1:134326297257:ios:d1146fbbbb0f522a34bfb8',
    messagingSenderId: '134326297257',
    projectId: 'comments-app-b3777',
    storageBucket: 'comments-app-b3777.appspot.com',
    iosBundleId: 'com.example.commentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF0DH5LC41d5qA1n_hhx6GZTos-l9k-GI',
    appId: '1:134326297257:web:5d9a43d7ec8edf0434bfb8',
    messagingSenderId: '134326297257',
    projectId: 'comments-app-b3777',
    authDomain: 'comments-app-b3777.firebaseapp.com',
    storageBucket: 'comments-app-b3777.appspot.com',
    measurementId: 'G-NDKNNKTGYT',
  );
}
